Disable cellInfoCallback.
It just prints log message and it causes java.lang.NoClassDefFoundError error on older android versions because CellInfoCallback is not defined.